### ISSUE TITLE
Implement rollback

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/mw-gadget-rtrc#1]
Implement rollback.

---

Imported from meta.wikimedia.org:
- [[FEATURE REQUEST]: Rollback via ajax request](https://meta.wikimedia.org/wiki/User_talk:Krinkle/Tools/Archive#.5BFEATURE_REQUEST.5D:_Rollback_via_ajax_request)
- [Freaky Fries](https://meta.wikimedia.org/wiki/User:Freaky_Fries) opened this issue on 06:35, 8 September 2010 (UTC)

**Comment by he7d3r** [comment]
:+1:

**Comment by Krinkle** [comment]
I'll finish https://phabricator.wikimedia.org/T88044 / https://gerrit.wikimedia.org/r/242050 first so that the logic can be reused here.

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361270>.
