### ISSUE TITLE
Fix "Functionality not supported" warning in Chrome

### ISSUE THREAD

**Issue by he7d3r** [Krinkle/mw-gadget-rtrc#31]
When I acces [this page](https://pt.wikipedia.org/wiki/Usu%C3%A1rio%28a%29:Krinkle/RTRC?opt=%7B%22rc%22%3A%7B%22showAnonOnly%22%3Atrue%2C%22showUnpatrolledOnly%22%3Atrue%2C%22limit%22%3A100%2C%22namespace%22%3A0%7D%2C%22app%22%3A%7B%22autoDiff%22%3Atrue%7D%7D&kickstart=1) using Google Chrome 34.0.1847.131 m (on Windows), I get the message "This program requires functionality not supported in this browser."
For some reason, ```$.support.modernizr4rtrc.generatedcontent``` seems to be false.

**Comment by Krinkle** [comment]
@he7d3r Let me know if you still get this with v1.0.0 or later.
