### ISSUE TITLE
MassPatrol unable to patrol redirects

### ISSUE THREAD

**Issue by sjoerddebruin** [Krinkle/mw-gadget-rtrc#39]
When it reaches a redirect on Wikidata, MassPatrol will stop working.

**Comment by XXN** [comment]
not only on wikidata. On wikipedias also. RTRC can't mark as patrolled created redirects. It follows redirects by default and there is no option to set RTRC to stay on redirect pages.

Can you fix this?

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361275>.
