### ISSUE TITLE
Include Flow contributions in the feed

### ISSUE THREAD

**Issue by mat-mo** [Krinkle/mw-gadget-rtrc#40]
How to reproduce:
1. go to https://he.wikipedia.org/wiki/%D7%A9%D7%99%D7%97%D7%AA_%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9:Amire80 and make an edit after enabling RTRC
2. the edit doesn't appear in RTRC interface.

**Comment by Krinkle** [comment]
This might be an issue in RTRC, but I'm quite sure it's probably a bug in Flow.

RTRC makes use of the MediaWiki API. If you can show me how and where Flow changes are listed on on https://he.wikipedia.org/wiki/Special:RecentChanges?namespace=3 or https://he.wikipedia.org/w/api.php?action=query&continue&list=recentchanges&rcnamespace=3, then I will work on including them in RTRC.

See also: https://www.mediawiki.org/wiki/User:Krinkle/Flow_review

**Comment by Krinkle** [comment]
Feel free to create a new task at <https://phabricator.wikimedia.org/tag/gadget-whatleaveshere/>.

Note that a proposal exists to undeploy the Flow extension, with content converted to wikitext. If this happens, then this feature might not be needed in RTRC. See also https://phabricator.wikimedia.org/T332022
