### ISSUE TITLE
The sidebar is not hidden correctly on RTL wikis

### ISSUE THREAD

**Issue by 5j9** [Krinkle/mw-gadget-rtrc#50]
On RTL wikis the sidebar is on the right... Here is an screenshot (from fawiki):

![new bitmap image](https://cloud.githubusercontent.com/assets/1055747/10720074/592428ea-7ba8-11e5-88d1-7761af7b51b5.png)

**Comment by Krinkle** [comment]
Closing in favour of #65. Will be fixed in the next release.
