### ISSUE TITLE
[Feature] WikiEditor and Semantic Forms

### ISSUE THREAD

**Issue by m-art-in** [Krinkle/mw-gadget-rtrc#51]
To use the costum script in combination with semantic form please
change
```js
    // Only on editpage
	if ($.inArray(mw.config.get('wgAction'), ['edit', 'submit']) !== -1) {
```
into
```js
    // Only on editpage
	if ($.inArray(mw.config.get('wgAction'), ['edit', 'submit', 'formedit']) !== -1) {
```
Thanks!

**Comment by Krinkle** [comment]
I'm not sure I understand this request. The RTRC gadget does not have the code you are referencing.

RTRC only initialises on `Special:BlankPage/RTRC`, and otherwise only when `wgAction === 'view'`.

**Comment by m-art-in** [comment]
I'm reffering to your script here: 
https://meta.wikimedia.org/w/index.php?title=User:Krinkle/Scripts/InsertWikiEditorButton.js&action=raw&ctype=text/javascript 
In you example page it's loading and check what kind of action is set. formedit would be fine here, too.

**Comment by Krinkle** [comment]
@m-art-in Okay. [Fixed!](https://meta.wikimedia.org/w/index.php?type=revision&diff=14339591&oldid=13219155)
