### ISSUE TITLE
MassPatrol gets stuck on already-patrolled changes

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/mw-gadget-rtrc#55]
Even when enabling the "Unpatrolled only" filter (which should be set by default when enabling MassPatrol) it's still possible to hit a patrolled change by accident if someone else patrols it between fetching the feed and the iteration over them.

In that case MassPatrol should ignore them and iterate over unpatrolled changes only. Basically we should make sure to filter client-side as well, not just in the query for the feed from the server.

**Comment by masumrezarock100** [comment]
When you are going to solve this?

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361279>.
