### ISSUE TITLE
Sidebar is broken for RTL in v1.3.0

### ISSUE THREAD

**Issue by eranroz** [Krinkle/mw-gadget-rtrc#65]
the sidebar goes into the page (left offset instead of right offset in RTL), making it impossible to use.

The .mw-rtrc-sidebar-toggleable #mw-panel rule should be splitted to .ltr version and .rtl version

**Comment by Krinkle** [comment]
@eranroz Thanks, I've confirmed the issue. This is a regression in release v1.3.0.

**Comment by mat-mo** [comment]
![rtrcscreenshot](https://cloud.githubusercontent.com/assets/4245366/18183261/39b4e7c6-709c-11e6-9f4f-83f2dbce3b82.png)
