### ISSUE TITLE
Add  show contributions of new accounts only checkbox

### ISSUE THREAD

**Issue by Arystanbek-kkwiki** [Krinkle/mw-gadget-rtrc#69]
Please add new function `show contributions of new accounts only `checkbox. 
![user contributions for new accounts](https://cloud.githubusercontent.com/assets/5893711/20876720/227d7d74-baee-11e6-87d8-8fca95acba5e.png)

**Comment by lgelauff** [comment]
Would love this feature! It's now a common setting in recent changes too.

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361282>.
