### ISSUE TITLE
RTRC features for Wikidata

### ISSUE THREAD

**Issue by QZanden** [Krinkle/mw-gadget-rtrc#71]
Hi Krinkle,
When I used RTRC a few months ago on Wikidata, it worked perfectly. Today I tried it again, but the Special:BlankPage/RTRC kept empty. Can you please fix it?
There is also a new wikiproject called counter-vandalism and it would be great if you could take a look there!
Have a nice day,
QZanden (same on-wiki)

**Comment by QZanden** [comment]
Hi Krinkle,
I was just a bit impatient. After 30 seconds the screen appeared, just as normal. 
But because wikidata is multilingual we (the wikiProject) would like to talk about features for the Wikidata version of RTRC.
https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_Counter-Vandalism here the link for the wikiproject.
QZanden

**Comment by Krinkle** [comment]
If this is still an issue please create a new task at https://phabricator.wikimedia.org/tag/gadget-rtrc/. Thanks!
