### ISSUE TITLE
Turning on 'Hide patrolled edits' breaks RTRC

### ISSUE THREAD

**Issue by mashedkeyboard** [Krinkle/mw-gadget-rtrc#72]
I get 'Downloading recent changes failed' every time I turn on 'Hide patrolled edits' in RTRC.

See the following examples to reproduce:

With 'Hide patrolled edits' on: https://en.wikipedia.org/wiki/Special:BlankPage/RTRC?opt=%7B%22rc%22%3A%7B%22unpatrolled%22%3Atrue%2C%22typeEdit%22%3Afalse%2C%22namespace%22%3A0%7D%2C%22app%22%3A%7B%22cvnDB%22%3Atrue%7D%7D

Without: https://en.wikipedia.org/wiki/Special:BlankPage/RTRC?opt=%7B%22rc%22%3A%7B%22unpatrolled%22%3Atrue%2C%22typeEdit%22%3Afalse%2C%22namespace%22%3A0%7D%2C%22app%22%3A%7B%22cvnDB%22%3Atrue%7D%7D

----
package: mw-gadget-rtrc v1.3.3
browser: edge 15.15063 (win)

**Comment by Krinkle** [comment]
@mashedkeyboard Most likely this is because your user account does not have the `patrol` right on en.wikipedia.org.

There is however still an issue with RTRC, which is that it is supposed to show the below warning for you, which it doesn't.

> code: permissiondenied
> info: You need the "patrol" or "patrolmarks" right to see distinction between patrolled and unpatrolled edits

**Comment by Cameron11598** [comment]
@Krinkle  I now get the same issue on Commons. Screen shot attached. 
![screen shot 2018-11-13 at 11 50 39 am](https://user-images.githubusercontent.com/20160457/48439243-a9577280-e73a-11e8-9bac-6ce79d66e9be.png)

**Comment by Arenlor** [comment]
This is still an active issue. [https://en.wikipedia.org/wiki/Special:BlankPage/RTRC?opt=%7B%22rc%22%3A%7B%22unpatrolled%22%3Atrue%7D%7D](url)

**Comment by Krinkle** [comment]
There is no error for me at that link. If this is still an issue, please create a new task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>. Thanks!
