### ISSUE TITLE
Firefox 57 update

### ISSUE THREAD

**Issue by seraphimsystem** [Krinkle/mw-gadget-rtrc#74]
RTRC has completely disappeared from the sidebar after the last firefox update for mint 18.2 - its still working with Firefox 45 but not 57

**Comment by Krinkle** [comment]
@seraphimsystem Do you still experience this issue?

If so, please share with me the following information:

* Version of RTRC (is shown on top in the grey menu bar at `Special:Blankpage/RTRC`).
* Version of Firefox.
* The website domain (e.g. he.wikipedia.org, or nl.wikipedia.org, or ..).

**Comment by Krinkle** [comment]
I'm closing this report due to inactivity. Please do let me know if you still experience it and can provide additional information.

Thanks!
