### ISSUE TITLE
New filter "Hide translations"

### ISSUE THREAD

**Issue by kaganer** [Krinkle/mw-gadget-rtrc#75]
Currently exist content project with installed "Translate Extension" - WikiSpecies.
In the classic "Recent Changes" now exist filter "Not translations", that is useful for hide changes in the translation namespace (that is flooded RC and interfere with normal patrolling works). 

Proposed similar filter for RTRC tool (with name like "Hide translations").

See [relevant topic in WikiSpecies](https://species.wikimedia.org/w/index.php?title=Wikispecies:Administrators%27_Noticeboard#Translators_and_Unpatrolled_Pages).

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T361284>.
