### ISSUE TITLE
"Link to current settings" in 1.3.6-pre does not work

### ISSUE THREAD

**Issue by jdxAtGitHub** [Krinkle/mw-gadget-rtrc#80]
At least  on Commons. It is just **https://commons.wikimedia.org/wiki/Special:BlankPage/RTRC?opt=**, i.e. options string is empty.

**Comment by Krinkle** [comment]
Thanks. I'll get this fixed as soon as possible. Meanwhile, I'ver restored the deployed version of RTRC to v1.3.5.

**Comment by Krinkle** [comment]
Thanks. I'll get this fixed as soon as possible.

I have reversed the deployed version of RTRC from v1.3.6-pre to v1.3.5.
