### ISSUE TITLE
Userfilter does not work for IP addresses

### ISSUE THREAD

**Issue by jdx-gh** [Krinkle/mw-gadget-rtrc#89]
Just "No relevant changes for your settings" is displayed. For usernames (registered users) it works as expected. I am quite sure that yesterday everything was fine. I use RTRC on Commons.

**Comment by Krinkle** [comment]
It seems to work for me. Both with IPv4 and IPv6 examples. If this still an issue, please create a new task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>.

<img height="200" alt="Screenshot" src="https://github.com/Krinkle/mw-gadget-rtrc/assets/156867/f5578f28-7ecf-4bc0-be1d-5e33c464ce2a">

<img height="200" alt="Screenshot" src="https://github.com/Krinkle/mw-gadget-rtrc/assets/156867/382e2fee-0c3b-4c81-b3d8-2ef28fa95a38">
