### ISSUE TITLE
Fire mw.hook for diff load (once supported in mediawiki)

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/mw-gadget-rtrc#9]
MediaWiki core already implements this for page conten with `wikipage.content`. I expect other hooks will follow soon for things like portlets, categories and diffs.

When it does, we can fire those hooks from RTRC so that other gadgets can universally add utility links (e.g. "rollback AGF", "rollback VANDAL" etc. like Twinkle does) regardless of whether the diffs are shown by MediaWiki or by RTRC.

----
Originally requested on [meta.wikimedia.org](https://meta.wikimedia.org/w/index.php?title=User_talk:Krinkle/Tools&oldid=5916665#.5BFEATURE.5D:_Ability_to_add_callbacks_in_RTRC) by [Matanya](https://meta.wikimedia.org/wiki/User:Matanya) on 31 January 2011.

**Comment by he7d3r** [comment]
This also blocks [integration with WikEd](https://pt.wikipedia.org/w/index.php?title=Usu%C3%A1rio%28a%29_Discuss%C3%A3o:He7d3r&oldid=44950879#RTRC) (which turns URLs appearing on a diff into clickable links).

**Comment by he7d3r** [comment]
There is a hook `wikipage.diff` since https://github.com/wikimedia/mediawiki/commit/9cfb9cb9fba4dcfd25a0924237681b7cc86a20df. See also [T53583](https://phabricator.wikimedia.org/T53583).
