### ISSUE TITLE
Loading changes failed

### ISSUE THREAD

**Issue by Amirufc** [Krinkle/mw-gadget-rtrc#93]
Downloading recent changes failed
Please check the settings above and try again. If you believe this is a bug, please let me know.

----
package: mw-gadget-rtrc v1.3.4
browser: chrome 87.0.4280.66 (win)

**Comment by Krinkle** [comment]
On which wiki does this happen? Does it happen every time you open `/wiki/Special:Blankpage/RTRC`, or only sometimes or with certain options?

**Comment by Krinkle** [comment]
If this is still an issue, please create a new task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>. Thanks!
