### ISSUE TITLE
Twinkle Rollback buttons do not show up

### ISSUE THREAD

**Issue by bas-dehaan** [Krinkle/mw-gadget-rtrc#95]
When looking at a diff in RTRC the Twinkle [Rollback] and [Vandalism] buttons do not show up like they would do on the 'regular' recent changes or looking at a 'regular' diff.

Diff in RTRC:
<img width="1386" alt="RTRC Diff" src="https://user-images.githubusercontent.com/9017270/123873674-27daa000-d937-11eb-8ae7-ebba4be37dc1.png">
Regular Diff:
<img width="1207" alt="Regular Diff" src="https://user-images.githubusercontent.com/9017270/123873677-28733680-d937-11eb-8df8-db8c37acd4f6.png">

**Comment by Krinkle** [comment]
Originally added as feature in https://github.com/Krinkle/mw-gadget-rtrc/issues/9.

Looks like something somewhere stopped working.

**Comment by Krinkle** [comment]
Discussion around this continues at <https://github.com/wikimedia-gadgets/twinkle/issues/1431>. If there is something we can do in RTRC to help with this, please create a new task at <https://phabricator.wikimedia.org/tag/gadget-rtrc/>.
